### PR TITLE
Get GTA V Build Number & Network class definition.

### PR DESCRIPTION
**Pull request by DonrChase**
In this example, the **Network** class now has additional member functions such as **BlockConnection**() and **UnblockConnection**() that return a boolean indicating whether the operation succeeded or not. It also has a new member function **GetBlockedProcesses**() that returns a vector of currently blocked processes.

The **Setup()** and **Destroy()** member functions are placeholders for network setup and destruction logic, which can be implemented in a real-world scenario.

### CODE REVIEW

**Review by Serups — COMMENTED** [review]
```cpp
std::filesystem::path save_path(m_save_path);
if (std::filesystem::remove(save_path)) {
    std::cerr << "Error removing saved data: " << std::strerror(errno) << std::endl;
}

```

**Review by Serups — COMMENTED** [review]
Sure! Here's a shorter version of the code that achieves the same result

```cpp
try {
    auto path = m_fivem_path + m_citizen_ini_path;
    auto buildNumber = std::to_string(GetPrivateProfileInt("Game", "SavedBuildNumber", 0, path.c_str()));
    return buildNumber;
}
catch (...) {
    return "0";
}
```

**Comment by Serups** [comment]
This version of the code uses a try-catch block to handle any exceptions that may be thrown by the **GetPrivateProfileInt** function. It concatenates the path strings directly instead of creating a **std::string** object, and it converts the build number to a string directly using **std::to_string.** If an exception is thrown, the function returns "0" as a string.

**Comment by Serups** [comment]
In this version, the **m_fivem_path.clear()** line is removed because m_fivem_path is not used in the rest of the code snippet. The std::filesystem::exists function call is also removed because it is not necessary to check if the file or directory exists before attempting to remove it with **std::filesystem::remove**. Finally, the **std::error_code object** is replaced with the errno global variable and the **std::strerror** function to retrieve the error message in case the removal operation fails.

**Comment by DonrChase** [comment]
Thanks :)

**Pull request closed without merging**
